export const ProductList = [
  {
    id: 1,
    nome: "Banheira Relax Luxo",
    descricao: "Banheira confortável com design moderno, ideal para relaxar.",
    preco: 3299.99,
    categoria: "Banheiras",
    imagem: "https://via.placeholder.com/300x200.png?text=Banheira+Relax",
    avaliacao: 4.8,
    estoque: 12,
    destaque: true,
  },
  {
    id: 2,
    nome: "Banheira Compacta",
    descricao: "Perfeita para espaços pequenos, sem abrir mão do conforto.",
    preco: 1999.99,
    categoria: "Banheiras",
    imagem: "https://via.placeholder.com/300x200.png?text=Banheira+Compacta",
    avaliacao: 4.2,
    estoque: 8,
    destaque: false,
  },
  {
    id: 3,
    nome: "Banheira Spa Duo",
    descricao: "Espaçosa e equipada com sistema de hidromassagem.",
    preco: 5499.99,
    categoria: "Banheiras",
    imagem: "https://via.placeholder.com/300x200.png?text=Banheira+Spa+Duo",
    avaliacao: 4.9,
    estoque: 5,
    destaque: true,
  },
  {
    id: 4,
    nome: "Banheira Econômica",
    descricao: "Solução prática e econômica para seu banheiro.",
    preco: 1299.99,
    categoria: "Banheiras",
    imagem: "https://via.placeholder.com/300x200.png?text=Banheira+Econômica",
    avaliacao: 4.0,
    estoque: 20,
    destaque: false,
  },
  {
    id: 5,
    nome: "Banheira Luxo Premium",
    descricao: "Com acabamentos premium, a escolha perfeita para quem busca sofisticação.",
    preco: 7999.99,
    categoria: "Banheiras",
    imagem: "https://via.placeholder.com/300x200.png?text=Banheira+Luxo+Premium",
    avaliacao: 5.0,
    estoque: 3,
    destaque: true,
  },
];
